name: k4GenCITests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v1
      with:
        cvmfs_repositories: 'sw.hsf.org,sw-nightlies.hsf.org,sft-nightlies.cern.ch,sft.cern.ch,geant4.cern.ch'
    - name: Start container
      run: |
        docker run -it --name CI_container -v ${GITHUB_WORKSPACE}:/Package -v /cvmfs:/cvmfs:shared -d clicdp/cc7-lcg /bin/bash
    - name: Setup container
      run: |
        docker exec CI_container /bin/bash -c " ln -s /usr/lib64/liblzma.so.5.2.2 /usr/lib64/liblzma.so;"

    - name: Setup Spack
      run: |
        docker exec CI_container /bin/bash -c 'cd ./Package; curl -L -o spack.tar.gz https://gitlab.cern.ch/key4hep/k4-deploy/-/jobs/artifacts/master/raw/key4hep-spack_centos7-cvmfs.tar.gz?job=setup_spack_push;\
        tar xfz spack.tar.gz && rm spack.tar.gz;'
    - name: Compile
      run: |
        docker exec CI_container /bin/bash -c 'cd ./Package; 
        source spack/share/spack/setup-env.sh;\
        spack dev-build k4gen@master;' # --test=all needs some work
    - name: Test
      # todo: need to figure out how to add runtime environment to ctest
      run: |
        docker exec CI_container /bin/bash -c 'cd ./Package; 
        source spack/share/spack/setup-env.sh;\
        spack load k4gen@master;\
        spack load cmake;\
        rm spack-build-*.txt;\
        cd spack-build-*;\
        ctest --output-on-failure;'
